### ISSUE TITLE
如何配置xml的代码高亮

### ISSUE THREAD

**Issue by TouchDeeper** [bilibili/vim-vide#11]
你好，请问如何像gedit选择xml格式，自动代码高亮呢？
另外，进群的答案为什么不是i呢？

**Comment by smileorigin** [comment]
> 你好，请问如何像gedit选择xml格式，自动代码高亮呢？
> 另外，进群的答案为什么不是i呢？

1. vim 默认就会自动高亮，如果是非 **.xml** 文件
    - 可以使用 `:set filetype=xml` 来手动设置文件类型为 **xml**
    - 可以在 **vimrc** 添加自动命令来自动处理，例如：`au BufNewFile,BufRead *.xxx set filetype=xml` 可以设置 **.xxx** 后缀的文件类型为 **xml**
1. 进群的答案？？？

**Comment by TouchDeeper** [comment]
1. 没问题了。
2. 不是有个qq群吗，进群需要答vim进入插入模式的方法
